# Generated by Django 3.0.2 on 2021-04-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210425_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='series',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
