# Generated by Django 3.0.2 on 2021-04-25 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='fifth_best',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fifth_book', to='home.Book'),
        ),
        migrations.AddField(
            model_name='person',
            name='first_best',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_book', to='home.Book'),
        ),
        migrations.AddField(
            model_name='person',
            name='fourth_best',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth_book', to='home.Book'),
        ),
        migrations.AddField(
            model_name='person',
            name='second_best',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_book', to='home.Book'),
        ),
        migrations.AddField(
            model_name='person',
            name='third_best',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_book', to='home.Book'),
        ),
    ]
