# Generated by Django 3.0.2 on 2021-04-25 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210425_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='fifth_best',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fifth_book', to='home.Book'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_best',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_book', to='home.Book'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fourth_best',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth_book', to='home.Book'),
        ),
        migrations.AlterField(
            model_name='person',
            name='second_best',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_book', to='home.Book'),
        ),
        migrations.AlterField(
            model_name='person',
            name='third_best',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_book', to='home.Book'),
        ),
    ]
