# Generated by Django 3.0.2 on 2021-04-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0008_auto_20200608_2021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
